name: timescaledb

# Keys

services:
  timescaledb:
    image: timescale/timescaledb-ha:pg16
    container_name: timescaledb
    environment:
      - POSTGRES_DB={POSTGRES_DB}
      - POSTGRES_PASSWORD={POSTGRES_PASSWORD}
      - POSTGRES_USER={POSTGRES_USER}
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  timescaledb_data:
